### ISSUE TITLE
login failed issue

### ISSUE THREAD

**Issue by weiztech** [nixdaemon/django-me#1]
i use this  session  settings

SESSION_ENGINE = 'django_me.sessions'
SESSION_SERIALIZER = 'django_me.sessions.BSONSerializer'

its return 'MetaDict' object has no attribute 'pk'
coul you let me know what i miss ?

**Comment by foodaemon** [comment]
sorry to be a bit late on commenting. you may want to use "login" function from django_me.mongo_auth.middlewares.py
since it has a fix for django's default "login" i.e. request.session[SESSION_KEY] = str(user.pk) instead of user._meta.pk.value_to_string(user)
example: https://gist.github.com/robintiwari/8a98acc764629a9ed09a

**Comment by foodaemon** [comment]
You can always reopen this ticket if you are still having this issue.

**Comment by weiztech** [comment]
Thanks its working now. :)
